baseurl = "https://nityuge.gitlab.io/center/hugocenter"
#baseurl = "https://www.center.yuge.ac.jp/"
title = "弓削商船高専　情報処理教育センター"
languageCode = "ja-jp"
paginate = "3" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Computer Educational Center"
  bio = "情報処理教育センターは以下の業務を行なっております。" #「教育用計算機システムの運用」、「管理ネットワークシステムの構築と運用」、「本校のセキュリティー対策」コンピュータ関係で疑問があれば、何でも質問してください。"
  avatar = "img/logo.gif"

[Params]
  subtitle = "Computer Education Center" # Subtitle of your site
  description = "" # Description of your site
  opengraph = true
  twitter_cards = true
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  post_navigation = true
  post_meta = ["date", "categories"] # Order of post meta information

[Params.sidebar]
  home = "left"   # Configure layout for home page
  list = "left"   # Configure layout for list pages
  single = "left" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 3 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[markup]
    defaultMarkdownHandler = "goldmark"
	
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
